# lightning.pytorch==2.3.2
seed_everything: 0
trainer:
  callbacks:
    - class_path: callback.ValidationCallback
    # - class_path: callback.ModelCheckpoint
  accelerator: gpu
  devices: [1]
  # accelerator: auto
  # devices: auto
  strategy: ddp_find_unused_parameters_true
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
  max_epochs: 5
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
ckpt_path: null
model:
  class_path: models.LargeLinear
  init_args:
    num_ifos: 2
    num_timesteps: 200
    bottleneck: 8
data:
  class_path: dataloader.GwakBaseDataloader
  init_args:
    data_dir: /home/katya.govorkova/gwak2_background
    sample_rate: 2048
    kernel_length: 0.09765625
    psd_length: 64
    fduration: 1
    fftlength: 2
    batch_size: 8
    batches_per_epoch: 8
    num_workers: 5
    data_saving_file: output/gwak1/background.h5
